name: GitHub Actions Automation
run-name: CI script
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Python
        uses: actions/setup-python@v5.4.0
